import 'package:flutter/material.dart';
import '../../domain/models/calc_mode_entry.dart';

const List<CalcModeEntry> kCalcModeEntries = [
  CalcModeEntry(
    id: 'basic_calculator',
    title: '기본 계산기',
    description: '사칙연산 및 공학 계산',
    icon: Icons.calculate,
    imagePath: 'assets/images/backgrounds/basic_calculator.png',
    order: 0,
  ),
  CalcModeEntry(
    id: 'exchange_rate',
    title: '환율 계산기',
    description: '실시간 전 세계 환율 변환',
    icon: Icons.currency_exchange,
    imagePath: 'assets/images/backgrounds/exchange_rate.png',
    order: 1,
  ),
  CalcModeEntry(
    id: 'unit_converter',
    title: '단위 변환기',
    description: '길이, 무게, 넓이 등 변환',
    icon: Icons.straighten,
    imagePath: 'assets/images/backgrounds/unit_converter.png',
    order: 2,
  ),
  CalcModeEntry(
    id: 'vat_calculator',
    title: '부가세 계산기',
    description: '부가세 포함/별도 계산',
    icon: Icons.receipt_long,
    imagePath: 'assets/images/backgrounds/vat_calculator.png',
    order: 3,
  ),
  CalcModeEntry(
    id: 'age_calculator',
    title: '나이 계산기',
    description: '만 나이, 띠, 별자리 확인',
    icon: Icons.cake,
    imagePath: 'assets/images/backgrounds/age_calculator.png',
    order: 4,
  ),
  CalcModeEntry(
    id: 'date_calculator',
    title: '날짜 계산기',
    description: '디데이 및 날짜 간격 계산',
    icon: Icons.calendar_month,
    imagePath: 'assets/images/backgrounds/date_calculator.png',
    order: 5,
  ),
  CalcModeEntry(
    id: 'loan_calculator',
    title: '대출 계산기',
    description: '월납입금 및 총이자 계산',
    icon: Icons.account_balance,
    imagePath: 'assets/images/backgrounds/loan_calculator.png',
    order: 6,
  ),
  CalcModeEntry(
    id: 'salary_calculator',
    title: '실수령액 계산기',
    description: '연봉 기준 세후 실수령액 계산',
    icon: Icons.payments,
    imagePath: 'assets/images/backgrounds/salary_calculator.png',
    order: 7,
  ),
  CalcModeEntry(
    id: 'discount_calculator',
    title: '할인 계산기',
    description: '할인율 적용 최종금액 계산',
    icon: Icons.local_offer,
    imagePath: 'assets/images/backgrounds/discount_calculator.png',
    order: 8,
  ),
  CalcModeEntry(
    id: 'dutch_pay',
    title: '더치페이 계산기',
    description: '인원수별 1/N 금액 계산',
    icon: Icons.group,
    imagePath: 'assets/images/backgrounds/dutch_pay.png',
    order: 9,
  ),
  CalcModeEntry(
    id: 'rent_calculator',
    title: '전월세 계산기',
    description: '전세↔월세 전환 및 보증금 계산',
    icon: Icons.apartment,
    imagePath: 'assets/images/backgrounds/rent_calculator.png',
    order: 10,
  ),
  CalcModeEntry(
    id: 'acquisition_tax',
    title: '취득세 계산기',
    description: '매매가 기준 취득세 계산',
    icon: Icons.real_estate_agent,
    imagePath: 'assets/images/backgrounds/acquisition_tax.png',
    order: 11,
  ),
  CalcModeEntry(
    id: 'bmi_calculator',
    title: 'BMI 계산기',
    description: '신장·체중 기준 체질량지수 계산',
    icon: Icons.monitor_weight,
    imagePath: 'assets/images/backgrounds/bmi_calculator.png',
    order: 12,
  ),
];
